name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Nix
      uses: DeterminateSystems/nix-installer-action@v4
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Run Nix Cache (optional, for faster builds)
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Enter Nix shell environment
      run: nix develop --extra-experimental-features 'nix-command flakes' -c $SHELL

    # Download and install firtool manually
    - name: Download and install firtool
      run: |
        FIRTOOL_URL="https://github.com/llvm/circt/releases/download/v1.0.0/circt-bin-ubuntu-20.04.tar.gz"
        curl -L $FIRTOOL_URL -o circt.tar.gz
        mkdir -p circt
        tar -xzf circt.tar.gz -C circt --strip-components 1
        sudo mv circt/bin/firtool /usr/local/bin/
        sudo chmod +x /usr/local/bin/firtool

    - name: Verify firtool installation
      run: firtool --version

    - name: Set output environment variable
      run: export output=out

    - name: Run sbt command
      run: sbt run
