name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Nix
      uses: DeterminateSystems/nix-installer-action@v4
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Run Nix Cache (optional, for faster builds)
      uses: DeterminateSystems/magic-nix-cache-action@v2
    
    - name: Enter Nix shell environment
      run: nix develop --extra-experimental-features 'nix-command flakes' -c $SHELL

    - name: Set output environment variable
      run: export output=out

    - name: Run sbt command
      run: sbt run
